# Generated by Django 3.2.5 on 2021-07-08 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_player_tree'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tree',
            old_name='player',
            new_name='player_id',
        ),
    ]
