# Generated by Django 3.2.5 on 2021-07-08 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_rename_player_tree_player_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='player_id',
            field=models.IntegerField(),
        ),
    ]
