# Generated by Django 3.2.5 on 2021-07-08 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_player_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tree',
            old_name='player_id',
            new_name='name',
        ),
    ]
