# Generated by Django 3.2.5 on 2021-07-09 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_alter_tree_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='chief',
        ),
        migrations.AddField(
            model_name='employee',
            name='chief',
            field=models.ManyToManyField(blank=True, null=True, to='employees.Employee'),
        ),
    ]
