# Generated by Django 3.2.5 on 2021-07-12 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_genre_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
    ]
