# Generated by Django 3.2.5 on 2021-07-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0016_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(max_length=99, verbose_name='Должность'),
        ),
    ]
