# Generated by Django 3.2.5 on 2021-07-12 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0018_auto_20210712_2046'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='user',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
        migrations.DeleteModel(
            name='Tree',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
